### ISSUE TITLE
Error 500 in wrong situation

### ISSUE THREAD

**Issue by LexNastin** [webtor-io/helm-charts#9]
# I'm getting the error 500 in the wrong place
## Problem
When I try to go to my instance of the server at `http://192.168.68.204:32477`, I seem to be getting the `HTTP 200` status where in the manual it explains that I should get `HTTP 500`, and strangely enough when the webtor player goes to `http://<baseUrl>/show?<some_metadata_about_torrent>`, I seem to apparently be getting `HTTP 500` there, how could I fix this?

**Edit:** Just to be clear, I have checked the default `https://webtor.io` URL, and it appears to be working.

## Screenshots
![image](https://user-images.githubusercontent.com/32967396/114944410-7223a900-9e3f-11eb-83da-9c10c8862122.png)
![image](https://user-images.githubusercontent.com/32967396/114944683-f9711c80-9e3f-11eb-94a6-5dc9eeca5ae2.png)
![image](https://user-images.githubusercontent.com/32967396/114944741-1148a080-9e40-11eb-932b-8338d021c547.png)
![image](https://user-images.githubusercontent.com/32967396/114944592-caf34180-9e3f-11eb-832d-b3b2f9ee4f01.png)
![image](https://user-images.githubusercontent.com/32967396/114944469-9089a480-9e3f-11eb-918b-d385d4189898.png)
![image](https://user-images.githubusercontent.com/32967396/114944546-b151fa00-9e3f-11eb-83cf-9da2f96c5ab8.png)

**Comment by vintikzzz** [comment]
I have switched HTTP status to 200 because it confuses everybody (readme fixed already).

You have setted up backend API, and now you can connect to it with one of these SDK's
https://github.com/webtor-io/platform-sdk-js
https://github.com/webtor-io/platform-sdk-php

Also you can find some examples there
https://github.com/webtor-io/platform-sdk-js/tree/master/example

Webtor frontend that you can see at https://webtor.io is not opensourced and it is not planned.

**Comment by LexNastin** [comment]
Ahhh, thanks so much, now it makes sense why there were 2 separate things, will checkout tomorrow morning and report on how it goes. Have a good day 😀

**Comment by LexNastin** [comment]
Hey, just came back here because I remembered about this, I tried it a day or 2 ago, it seemed to work, huge thanks! 😄
